version: '3'
services:
  composer:
    image: composer:latest
    environment:
      - COMPOSER_CACHE_DIR=/app/var/cache/composer
    volumes:
      - .:/app
    restart: never
  php:
    image: php:8.1-cli
    restart: never
    volumes:
      - .:/app
    working_dir: /app
  phpunit:
    image: php:8.1-cli
    restart: never
    volumes:
      - .:/app
    working_dir: /app
    entrypoint: vendor/bin/phpunit
  phpstan:
    image: php:8.1-cli
    restart: never
    volumes:
      - .:/app
    working_dir: /app
    entrypoint: vendor/bin/phpstan
  phpcsfixer:
    image: php:8.1-cli
    restart: never
    volumes:
      - .:/app
    working_dir: /app
    entrypoint: vendor/bin/php-cs-fixer
